# -*- coding: utf-8 -*-
"""AiHello_Challenge2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1szWEfUbb0RGy4YyASzZ_Qrmq8ND79ou4
"""

#DATA PREPARED FOR EMPLOYER PROFILES
employers = [
    {
        "title": "Senior WordPress Developer",
        "description": """
        We are looking for a skilled 'WordPress Website Developer' with expertise in end-to-end development, deployment, and maintenance of dynamic websites. Join our innovative team and contribute to creating outstanding digital experiences.

        Key Responsibilities:

        1. Website Development: Design, develop, and maintain responsive WordPress websites that align with business objectives and user needs.
        2. Customization: Customize themes, plugins, and templates to meet specific project requirements.
        3. Integration: Implement third-party APIs, payment gateways, CRM tools, and other integrations as needed.
        4. Optimization: Ensure website performance, speed, and security are up to industry standards.
        5. Deployment: Manage end-to-end deployment, including hosting, DNS configuration, and server management.
        6. Troubleshooting: Debug and resolve technical issues promptly.
        7. Collaboration: Work closely with designers, content creators, and other team members to deliver cohesive solutions.
        8. Maintenance: Provide ongoing support, updates, and enhancements to existing websites.

        Required Skills & Qualifications:
        Technical Expertise:
        - Proficiency in WordPress, including custom theme and plugin development.
        - Strong knowledge of PHP, HTML5, CSS3, JavaScript, and MySQL.
        - Familiarity with modern frameworks like React, Vue.js, or Angular is a plus.
        Deployment Experience:
        - Hands-on experience with version control systems (e.g., Git).
        - Proficient in server setup, hosting environments, and DNS configuration.
        - Knowledge of CI/CD pipelines is advantageous.
        Problem-Solving:
        - Ability to identify, diagnose, and resolve performance bottlenecks and security issues.
        Soft Skills:
        - Strong communication and teamwork skills.
        - Excellent time management and ability to meet deadlines.

        Preferred Qualifications:
        - Experience with SEO, accessibility standards, and analytics integration.
        - Understanding of cloud services like AWS, Google Cloud, or Azure.

        Who can apply
        1. Candidates with minimum 1 years of experience.
        2. Those who are from or open to relocate to Greater Noida and neighboring cities
        Other requirements
        B.tech
        Experience with SEO, accessibility standards, and analytics integration.
        Understanding of cloud services like AWS, Google Cloud, or Azure.
        Salary
        Annual CTC: ₹ 5,00,000 - 6,00,000 /year
        """,
        "location": "Greater Noida and neighboring cities",
        "salary_range": (500000, 600000),
        "education": "B.tech",
        "experience": 1
    },
    {
        "title": "Graphic Designer",
        "description": """
        Key responsibilities:

        1. Create visually appealing graphics for various platforms including websites, social media and print.
        2. Collaborate with the marketing and content teams to develop design concepts and execute projects.
        3. Use design tools such as Figma and Adobe Illustrator to produce high-quality designs.

        Who can apply
        1. Candidates with minimum 1 years of experience.
        2. Those who are from or open to relocate to Noida and neighboring cities
        Other requirements
        1. Experience with other tools such as Adobe Photoshop and InDesign.
        2. Basic understanding of web design principles and HTML/CSS
        3. Ability to work collaboratively in a team environment.
        Salary
        Annual CTC: ₹ 2,00,000 - 3,00,000 /year
        Number of openings
        5
        """,
        "location": "Noida and neighboring cities",
        "salary_range": (200000, 300000),
        "education": None,
        "experience": 1
    },
    {
        "title": "Cinematographer",
        "description": """
        As a Cinematographer at Bluntly Streaming, you will have the exciting opportunity to showcase your skills in video making, direction, video editing, Adobe Premiere Pro, photography, and Adobe Photoshop. Your creativity and technical expertise will play a crucial role in producing high-quality content for our streaming platform.

        Key responsibilities:

        1. Collaborate with the content team to develop creative concepts and storyboards for video projects and direct it
        2. Shoot and capture high-quality video footage using professional equipment and techniques.
        3. Edit video footage to produce compelling and engaging content for our platform.
        4. Utilize Adobe Premiere Pro and Adobe Photoshop to enhance video quality and visual appeal.
        5. Ensure all video content meets brand standards and guidelines.
        6. Stay up-to-date on industry trends and technologies to continuously improve our video production process.
        7. Work closely with the post-production team to finalize and deliver completed projects on time.

        If you are passionate about cinematography and have a keen eye for detail, we want you to join our innovative team at Bluntly Streaming. Your talent and expertise will help us deliver exceptional content to our audience. Apply now to be a part of our dynamic team!

        Salary
        Probation:
        Duration: 1 month
        Salary during probation: ₹10,000 - 15,000 /month (only for freshers)
        After probation:
        Annual CTC: ₹ 2,00,000 - 3,00,000 /year
        Perks
        Informal dress code Free snacks & beverages
        Number of openings
        2
        """,
        "location": None,
        "salary_range": (200000, 300000),
        "education": None,
        "experience": 0
    },
    {
        "title": "Financial Sales Officer",
        "description": """
        Key responsibilities:

        1. Getting familiar with the underwriting criteria of our 15 partner banks, which include SBI, BOB, ICICI, Axis Bank, HDFC, etc.
        2. Screen the education loan applications, advise students on the documentation, and coordinate with bank staff for smooth processing of the education loan.
        3. Work on solving student's queries.
        4. Manage the process from eligibility to the sanctioning of the loan.
        5. This job requires you to be on calls for longer hours, as you will deal with students virtually.

        To summarize, this job consists of 20% Banking Finance, 40% Customer facing operations, 40% Business Development and Sales.
        Skill(s) required
        English Proficiency (Spoken)

        Who can apply
        1. Those who are from or open to relocate to Kurnool, Visakhapatnam, Warangal, Secunderabad, Hyderabad, Uppal, Begumpet, Rai Durg, Amberpet, Srikakulam and neighboring cities
        Other requirements
        1. Any graduate or postgraduate with different specializations from the 2023 & 2024 batches is good to go.
        2. No prior experience is required or candidates with 1 year of work experience are also eligible.
        Salary
        Annual CTC: ₹ 4,00,000 - 4,30,000 /year
        Perks
        Informal dress code 5 days a week Free snacks & beverages
        Number of openings
        20
        """,
        "location": "Kurnool, Visakhapatnam, Warangal, Secunderabad, Hyderabad, Uppal, Begumpet, Rai Durg, Amberpet, Srikakulam and neighboring cities",
        "salary_range": (400000, 430000),
        "education": "Any graduate or postgraduate",
        "experience": 0
    },
    {
        "title": "Associate Content Writer",
        "description": """
        About the job
        Key responsibilities:

        1. Create clear, compelling, and well-researched content for various platforms, including websites, blogs, social media, email newsletters, and marketing materials.
        2. Develop content strategies to meet business objectives, attract target audiences, and enhance brand voice.
        3. Collaborate with marketing, design, and product teams to produce content that aligns with company goals.
        4. Optimize content for SEO to increase organic traffic and improve search engine rankings.
        5. Edit and proofread content to ensure clarity, consistency, and accuracy.
        6. Stay updated on industry trends, competitor activities, and emerging content formats to keep content fresh and relevant.
        7. Manage content calendars and meet deadlines while maintaining a high standard of quality.
        8. Analyze performance metrics and adjust content strategies accordingly.

        Note:

        1. Working says: Monday to Saturday.
        2. Timings: 10 AM to 7 PM.
        3. Work from the office: Monday, Wednesday and Friday.
        4. Work from home: Tuesday, Thursday and Saturday
        5. A laptop is a mandatory requirement for this position
        Skill(s) required
        Blogging Creative Writing Digital Marketing English Proficiency (Spoken) English Proficiency (Written) Search Engine Optimization (SEO) Social Media Marketing

        Salary
        Annual CTC: ₹ 2,00,000 - 4,00,000 /year
        Perks
        Informal dress code Free snacks & beverages
        Number of openings
        1
        """,
        "location": None,
        "salary_range": (200000, 400000),
        "education": None,
        "experience": 0
    }
]

candidates = [
    {
        "name": "PERSON1",
        "description": """
        Technical Skills
        Languages: Python (NumPy, Pandas), PHP 7+, Bash, Java, JavaScript (ES6+), C++, MATLAB
        Frontend: React.js, HTML5/CSS3
        Backend: Express.js, Node.js, Flask, PHP
        DevOps & Tools: Git, Docker, Apache, Nginx, PyCharm
        Databases: MySQL, PostgreSQL, MongoDB, SQLite
        Operating Systems: Linux, MacOS, Windows
        Experience
        Research Intern June 2024 – Present
        NIT Surathkal Mangalore, Karnataka
        • Developing a federated learning framework enabling secure, decentralized model training, expecting reduction in data-sharing
        risks upto 40%.
        • Enhancing a colon cancer detection model accuracy by 18% by addressing data limitations through merging public and private
        datasets and employing GANs for data augmentation and Improving model performance on imbalanced datasets by 10% using
        transfer learning techniques and standardized evaluation metrics through proposed benchmarks.
        Research Intern June 2024 – Sep 2024
        IIT Jodhpur Jodhpur, Rajasthan
        • Conducted a comparative study of DiSMEC, Bonsai, and AnnexML, enhancing understanding of Extreme Multi-label
        Classification techniques and Authored progress reports utilizing LaTeX and presented research findings via technical PPTs.
        • Developed and evaluated tree-based and embedding-based XMC models using C++ and MATLAB, refining loss functions and
        ensemble methods to improve classification accuracy, leading to a 15% improvement in model performance through optimization.
        Analyzed and processed on a dataset having more than 4,000 labels and over 15k data points.
        Android Developer Intern July 2023 – Aug 2023
        MSA Tech Solution Faridabad, Haryana
        • Gained proficiency in using Java, Gradle, Android SDK and Designed dynamic and responsive UI layouts using XML and
        implemented Navigation Toolbar and RecyclerView, reducing app crash rates by 20% through optimized code practices.
        • Used Jetpack Compose for declarative UI development, improving development speed and consistency by 30%.
        Projects
        Influencer Management Portal | Python, Flask, SQLite, Jinja2 July 2024 – Aug 2024
        • Engineered a robust web application using PHP, Apache, and MySQL with session management, authentication, and user
        permissions. Designed with MVC architecture and containerized using Docker for efficient deployment.
        Application Tracking System with Data Summarization | Machine Learning, NLP June 2024 – Present
        • Developing an NLP-powered application to grade and summarize resumes, leveraging machine learning to optimize them for job
        descriptions and enhance relevance.
        User Management System | PHP , Apache, MySQL, Docker July 2023 – Nov 2023
        • Developed a web application using PHP, Apache, and MySQL with session management, authentication, and authorization.
        Implemented MVC architecture and containerized with Docker for streamlined deployment.
        Freelancing and Personal Automation Scripts | Python, Bash May 2022 – Present
        • Web Scraping Tools: Developed Python-based scrapers to efficiently extract documents from government websites and
        retrieve email addresses from educational institutions, streamlining data collection processes.
        • Mobile Game Automation: Built a script to automate repetitive tasks in the game Survivor.io, enhancing gameplay efficiency
        and reducing manual effort.
        • PDF Data Processing: Created a script to extract data from PDFs and transform it into interpretable formats for
        streamlined analysis and reporting.
        • Automated Job Applications: Currently developing a Python-based script leveraging SMTP to automate job application
        submissions, improving application efficiency and tracking.

        Salary desired: more than 10 lakhs per annum
        """,
        "location": None,
        "salary_desired": 1000000,
        "education": None,
        "experience": 0
    },
    {
        "name": "PERSON2",
        "description": """
        Senior Wordpress Developer
        05/2016 - PRESENT
        San Francisco, CA
        Implements designed layout with attention to details such as style and size of type, photographs, graphics, animation, etc. for the web and various other media
        Ensures all items are properly reviewed by internal compliance and adheres to brand philosophy and style guidelines
        Exhibits follow-up skills in order to ensure projects are completed accurately, timely and within budget constraints
        Develops new website features and seeks out existing solutions to meet client needs
        Executes web-based production of marketing and advertising products
        Ensures cross browser compatibility
        Health, Dental, & Vision Insurance with generous employer funding for employees and dependents
        Health Savings Account with generous employer funding
        Wordpress Developer
        08/2009 - 01/2016
        Philadelphia, PA
        Coordinating QA test plans
        Trouble-shooting and tracking issues, logs bugs, and collaborating with team to define site releases
        Maintaining a thorough understanding of how websites are constructed and how content is delivered online
        Working directly with Project Managers for creating and maintaining project schedules
        Working with a distributed team, integrating code with local and remote collaborators
        Staying abreast of new approaches in WordPress development
        Discerning feasibility of architectural and design prototypes
        Collaborating with team members in other disciplines to solve display, interaction and navigation challenges
        Defining browser requirements and contributing to testing scenarios
        Junior Wordpress Developer
        02/2003 - 07/2009
        Philadelphia, PA
        Company-sponsored short-term and long-term disability plans
        Company-sponsored life insurance
        Company-subsidized pet insurance
        Perks program for corporate discounts on a variety of services and items
        Annual stipend (prorated for new hires) for qualified expenses such as student loan debt, gym membership, home gym equipment, child care costs, and/or educational expenses within line of work
        Casual working environment
        Coding from PSD files into working pages, plugins, and themes within our Wordpress installs
        Playing a leadership role in taking projects from concept to launch, and coordinating design and development efforts
        Reviewing design and development work
        Professional Skills

        Excellent skills in building elegant professional websites while adhering to W3C standards using table-less layouts
        ● Requires knowledge and experience in own discipline; still acquiring higher level knowledge and skills
        Strong communications skills and the ability to work independently and as part of a team
        Team player that has excellent time management and communication skills
        Solid grammar, typing, writing and verbal communication skills
        Commit to constantly improving skills and staying current on developments and trends in the industry
        Use your coding and problem-solving skills to support web applications in a fast-paced, high-energy agile team environment

        Salary desired: more than 4 lakhs per annum

        Highest Studies: 12th Pass
        """,
        "location": None,
        "salary_desired": 400000,
        "education": "12th Pass",
        "experience": 0
    },
    {
        "name": "PERSON3",
        "description": """
        Experience
        Detroit, MI
        Gutkowski-Lakin
        PHP and HTML development outside of WordPress for landing pages, microsites, etc
        Utilizing JavaScript frameworks to implement website functionality
        Manage technical integration with third party services
        Ensure cross-browser, cross-platform, and multiple device type compatibility for all web solutions and perform any necessary QA on finished products
        Design and marketing materials development: enhance our brand presence (eBooks, flyers, booth design, web banners, PowerPoints, sales collateral, infographics, videos, etc.)
        Monitor uptime, hosting, and databases to ensure site is performing at maximum capacity
        Development expertise with custom post types, custom fields, plugins and themes for high-traffic Wordpress sites
        San Francisco, CA
        Rodriguez Group
        Responsible for the architecture, design and development of high volume web service applications
        Object oriented development is a plus
        Technically lead a team of more junior developers from design through release
        Deadline focused, detail oriented, well organized and self motivated
        Extensive knowledge in PHP (LAMP stack)
        Prepare business and technical documentation
        Work with Demand Generation team to make sure the website functions properly for SEO and SEM as well as the proper display of data
        San Francisco, CA
        Kassulke, Crona and Waelchi
        present
        Evaluate and implement new programming languages and technologies. Provide life-cycle management for software and code
        Assist and collaborate with other staff on technical matters. Conduct security reviews of applications written by other developers
        Implement and maintain content management systems (primarily WordPress, some Drupal), including installation, configuration, troubleshooting, and creation of custom SLS plugins and content types. Develop and deploy web applications and client-side web interface components that interact with relational database management systems that integrate with Stanford's web, authentication, and authorization infrastructure
        Architect, implement, and manage web-based applications, databases, and interfaces from initial architecture through development, test, and deployment
        Other duties may also be assigned
        Design, coordinate, and troubleshoot integrations, components, and infrastructures to run enterprise class website
        Education
        Bachelor’s Degree in Computer Science
        University of San Francisco
        Skills
        Ability to work independently and quickly
        Strong attention to detail
        Highly organized
        Good team player
        Polished and professional demeanor
        Able to work under tight deadlines with shifting priorities
        Solid PHP Experience
        Wordpress, PHP, Front End and some Back End knowledge
        Excellent communication skills
        QA testing experience/knowledge would be ideal
        """,
        "location": None,
        "salary_desired": None,
        "education": "Bachelor’s Degree in Computer Science",
        "experience": 0
    },
    {
        "name": "PERSON4",
        "description": """
        Adobe January 2020 - Present
        Senior Graphic Designer
        Spearheaded a comprehensive rebranding initiative, leveraging Adobe Creative Suite, which resulted in a 35% increase in brand recognition
        Initiated and managed cross-departmental collaborations that enhanced project efficiency by 25%, seamlessly integrating UX and graphic design elements
        Orchestrated the development and deployment of interactive digital assets, yielding a 45% surge in user engagement for major marketing campaigns
        Championed the adoption of new design techniques focused on inclusive design, extending market reach by tapping into underrepresented demographics
        Pioneered the use of data analytics tools in the creative process, optimizing content for a 30% uplift in conversion rates
        Canva June 2017 - December 2019
        Graphic Design Specialist
        Revolutionized client proposal visuals using Canva, enhancing pitch success rates by 22%
        Facilitated a series of design workshops for the creative team, improving overall productivity and design quality by 18%
        Curated a library of custom graphic elements and templates, reducing project turnaround time by 15%
        Self-Employed March 2014 - May 2017
        Freelance Graphic Designer
        Generated an average of $80k in annual revenue by delivering compelling visual designs for both web and print media
        Consistently maintained a client satisfaction rate of 95% through effective communication and on-time delivery of projects
        Coached.com August 2012 - February 2014
        Junior Graphic Designer
        Enhanced online learning materials by redesigning visuals, contributing to a 20% growth in user engagement
        Streamlined asset creation by introducing efficient use of Sketch, saving an estimated 5 hours per project
        EDUCATION
        Resume Worded Institute May 2012
        Master of Fine Arts - Graphic Design
        Thesis Project: 'Visual Branding in the Digital Age'
        Resume Worded University April 2016
        Adobe Certified Expert (ACE)
        Part-time; completed certification while freelancing
        SKILLS
        Design & Prototyping: Adobe Creative Suite (Expert), Sketch, Figma, InVision, Adobe XD, Principle
        Web Design: HTML5, CSS3, JavaScript (Basic), WordPress, Bootstrap, Webflow
        Branding & Visual Identity: Typography, Color Theory, Logo Design, Brand Guidelines, Visual Storytelling, Mood Boards
        Additional Tools: Microsoft Office Suite, Trello (Project Management), Slack, Asana, Dropbox
        OTHER
        Certifications: Certified Graphic Design Professional by the Graphic Design Certification board (2019)
        Professional Development: Attended 'Leaders in Design' summit (2021), Completed 'UX & Web Design' Master Course (2018)
        Awards: Recipient of the Canva Creative Excellence Award (2019)
        Industry Engagement: Regular speaker at Graphic Design Meetup Group, Mentor at Resume Worded Design Bootcamp
        """,
        "location": None,
        "salary_desired": None,
        "education": "Master of Fine Arts - Graphic Design",
        "experience": 0
    },
    {
        "name": "PERSON5",
        "description": """
        Google February 2018 - Present
        Lead Graphic Designer
        Overhauled the visual identity for Google’s internal training platform, leading to a 50% increase in monthly active users
        Directed and mentored a team of 10 designers, resulting in three junior designers being promoted within one year
        Implemented a design system using Figma that accelerated project workflows by 40%, enabling prompt campaign launches
        Cultivated a partnership with the marketing department, which drove a unified brand message and increased campaign reach by 60%
        Conceived a user-centered design approach that contributed to a 30% improvement in user experience scores for key products
        Mailchimp July 2014 - January 2018
        Graphic Design Manager
        Orchestrated Mailchimp’s visual strategy for email campaigns, which lifted open rates by an average of 19%
        Aligned design production with agile methodologies, yielding a 33% faster rollout for digital campaigns
        Resume Worded November 2011 - June 2014
        Graphic Designer
        Revitalized client resumes with dynamic layouts and infographics, resulting in a 50% increase in customer satisfaction
        Strengthened brand consistency across all marketing materials, boosting client engagement levels by 25%
        Pentagram January 2010 - October 2011
        Intern Graphic Designer
        Contributed innovative design concepts that were implemented in major brand projects, noted for enhancing visual appeal
        Refined technical skills in image editing and layout formation while assisting senior designers on high-profile client work
        EDUCATION
        Resume Worded Institute May 2016
        Master of Fine Arts - Graphic Design
        Specialization in User Experience Design
        Resume Worded Academic Center April 2011
        Adobe Certified Expert (ACE)
        Completed as Part-time
        """,
        "location": None,
        "salary_desired": None,
        "education": "Master of Fine Arts - Graphic Design",
        "experience": 0
    },
    {
        "name": "PERSON6",
        "description": """
        Coached.com March 2019 - Present
        Art Director
        Led the visual strategy for a national ad campaign, directly influencing a steady 40% increase in online traffic
        Managed and evolved brand guidelines, ensuring consistency across 100+ digital and print assets annually, resulting in a 20% reduction in brand confusion
        Negotiated with external vendors to procure high-quality printing services while decreasing costs by 10%
        Developed comprehensive storyboard designs which contributed to a 30% higher viewer retention rate on social media
        Instigated the transition to 3D design tools which modernized the brand’s image and increased customer interaction by 20%
        Dribbble August 2015 - February 2019
        Senior Graphic Designer
        Cultivated a user-centric design philosophy, improving website UX which propelled a 25% increase in daily page views
        Oversaw a team project to reimagine the brand's visual narrative, significantly bolstering user subscription rates by 35%
        Envato May 2012 - July 2015
        Graphic Designer
        Conceptualized and executed designs for digital assets that enhanced the user experience and contributed to a 15% growth in user base
        Optimized the use of InVision for prototype demonstrations, which sliced client approval times by 20%
        Behance February 2009 - April 2012
        Associate Graphic Designer
        Contributed to project brainstorming sessions which resulted in several award-winning designs
        Amplified the digital portfolio’s visibility, helping secure substantial clients through effective online showcase techniques
        EDUCATION
        Resume Worded University May 2014
        Master of Fine Arts - Graphic Design
        Culminating project featured in University's Annual Design Showcase
        Resume Worded Academic Center April 2009
        Bachelor of Arts - Visual Communication Design
        Graduated with Honors
        Participated in a collaborative project with local businesses
        SKILLS
        Design Software: Adobe Creative Suite (Expert), Sketch (Expert), InVision (Advanced), Figma (Advanced), CorelDRAW (Intermediate), Affinity Designer (Intermediate)
        Web Development: HTML5 (Proficient), CSS3 (Proficient), JavaScript (Basic), WordPress (Proficient), Webflow (Proficient), Bootstrap (Basic)
        Typography & Layout: Typeface Design (Advanced), Grid Systems (Advanced), Color Theory (Advanced), Editorial Design (Expert), Branding (Expert), Packaging Design (Advanced)
        Miscellaneous: Digital Illustration (Expert), Photo Editing (Expert), Print Production (Advanced), UX/UI Principles (Advanced), Motion Graphics (Basic), 3D Rendering (Basic)
        OTHER
        Certifications: Certified Graphic Designer from AIGA (2020), Google UX Design Certificate (2022)
        Professional Development: Attended 'Leaders in Design' Conference (2018), Participated in 'Branding Week' Workshop (2021)
        Awards: Winner of the Envato Monthly Design Challenge (June 2014), Dribbble Year’s Best User Interface Design (2016)
        Volunteering: Graphic Design Consultant for Non-Profits (2017-Present), Mentor for Young Creatives Program (2019-Present)
        """,
        "location": None,
        "salary_desired": None,
        "education": "Master of Fine Arts - Graphic Design",
        "experience": 0
    },
    {
        "name": "PERSON7",
        "description": """
        Summary
        Seasoned Investments Chief Sales Officer with over 10 years of experience, adept in developing and executing sales strategies that amplify revenue growth. Proven ability to foster strong client relationships, deliver compelling investment products and lead teams to exceed sales targets.
        Experience
        Senior Director of Investment Sales
        Capital Wealth Advisors
        06/2017 - Present
        Seattle, WA

        	•
        	Spearheaded the design and launch of innovative investment products, capturing a 20% market increase within the first year.
        	•
        	Established and nurtured high-value client partnerships resulting in a 35% rise in client retention rates.
        	•
        	Directed a team of 15 investment advisors, fostering a culture of success that led to a 50% increase in team sales figures over two years.
        	•
        	Implemented strategic sales training, enhancing team productivity by 30% and contributing to a 25% growth in quarterly revenue.
        	•
        	Negotiated and secured lucrative contracts with key industry players, boosting annual revenue by $5M.
        	•
        	Led company representation at top industry events, expanding business network by 150+ contacts and generating $10M in potential leads.

        Regional Sales Manager
        Premier Investment Services
        03/2014 - 05/2017
        Seattle, WA

        	•
        	Grew regional sales by 40% through strategic relationship building and targeted client outreach.
        	•
        	Launched a cross-functional initiative to streamline investment processes, increasing department efficiency by 25%.
        	•
        	Successfully increased market share by 20% through the development and promotion of client-centric investment solutions.
        	•
        	Collaborated with marketing to create impactful campaigns that resulted in a 30% increase in sales leads.
        	•
        	Achieved a 95% client satisfaction rate through delivery of bespoke investment advice and services.

        Investment Sales Team Lead
        Dynamic Investment Group
        08/2010 - 02/2014
        Seattle, WA

        	•
        	Managed and motivated a team of 10 sales professionals, achieving a team sales growth of 35% year-over-year.
        	•
        	Developed and executed sales strategies that penetrated new market segments, increasing overall revenue by 15%.
        	•
        	Led the creation of sales materials and presentations that significantly improved client engagement.
        	•
        	Facilitated the onboarding of major institutional clients, contributing to a 10% expansion of the client base.
        """,
        "location": None,
        "salary_desired": None,
        "education": None,
        "experience": 0
    },
    {
        "name": "PERSON8",
        "description": """
        Finance Analyst
        City, Country  •  (123) 456-789  •  yourname@resumeworded.com  •  linkedin.com/in/your-profile
        EXPERIENCE
        JPMorgan Chase March 2020 - Present
        Senior Finance Analyst
        Streamlined internal reporting processes by introducing advanced Excel models, resulting in a 20% reduction in monthly report generation time.
        Directed a team of 4 analysts to deliver comprehensive quarterly financial forecasts, identifying potential revenue streams that increased net income projections by 15%.
        Spearheaded the adoption of Tableau for data visualization, which enhanced the decision-making process by providing clearer insights into financial trends.
        Leveraged SQL databases for data extraction, transforming financial data infrastructure and improving data accuracy by 30%.
        Optimized capital budgeting through rigorous financial modeling, influencing investment decisions that led to a 10% growth in asset portfolio.
        Goldman Sachs October 2017 - February 2020
        Finance Analyst
        Conducted variance analysis that uncovered a 5% discrepancy in forecasted expenses, driving strategies to realign the $10M budget.
        Collaborated with cross-functional teams to perform due diligence on potential acquisitions, contributing to a deal that expanded the company's market share by 3%.
        Implemented a risk assessment framework that decreased financial exposure by identifying early warning signs in investment portfolios.
        Resume Worded May 2015 - September 2017
        Junior Finance Analyst
        Developed a dynamic financial dashboard used company-wide, enhancing visibility on KPIs and contributing to a 5% increase in operational efficiency.
        Analyzed competitive financial benchmarks and provided insights that informed strategic pricing decisions, improving profit margins by 2%.
        Coached.com June 2014 - April 2015
        Finance Intern
        Assisted with the automation of financial reporting processes using VBA, saving the team approximately 10 hours per month in manual data entry.
        EDUCATION
        Resume Worded Institute May 2020
        Master of Business Administration with a concentration in Finance
        Graduated with Honors, GPA: 3.8/4.0
        Resume Worded University May 2015
        Bachelor of Science in Economics
        Minors in Business Analytics and Accounting
        Coursework included Advanced Econometrics, Corporate Finance
        SKILLS
        Financial Analysis: Cash Flow Forecasting, Budget Management, Variance Analysis, ROI Analysis, Cost-Benefit Analysis, Financial Reporting (Advanced)
        Financial Modeling: DCF, NPV, Sensitivity Analysis, Financial Statement Analysis, Excel (Expert), VBA (Intermediate)
        Data Analysis: SQL (Intermediate), SAS (Intermediate), Tableau (Intermediate), Power BI (Intermediate), Financial Data Extraction, Data Validation
        Regulatory Compliance: Sarbanes-Oxley (SOX), Basel III, Dodd-Frank, SEC Filings, Compliance Reporting, Risk Assessment
        OTHER
        Certifications: Chartered Financial Analyst (CFA) - Level II (2019), Certified Financial Modeler (2021)
        Professional Development: Advanced Excel for Business Professionals (2018), Risk Management in Banking (2020)
        Awards: Goldman Sachs Excellence Award (2019), JPMorgan Performance Recognition (2021)
        Volunteering: Financial Literacy Workshop Facilitator (since 2018), Pro-Bono Financial Consultation for Non-Profits (since 2020)
        """,
        "location": None,
        "salary_desired": None,
        "education": None,
        "experience": 0
    },
    {
        "name": "PERSON9",
        "description": """
        EXPERIENCE
        Morgan Stanley February 2019 - Present
        Finance Manager
        Oversaw annual budgeting and quarterly forecasting for a $50M department, increasing forecasting accuracy to 98% through rigorous financial analysis.
        Introduced predictive modeling using Python, which enhanced cash flow management and improved short-term investment returns by 8%.
        Led financial strategy workshops for department heads, resulting in a unified approach to cost reduction that saved the company $2M annually.
        Managed and developed a high-performing finance team of 8, with two members promoted to senior roles within the first 18 months.
        Citibank January 2016 - January 2019
        Senior Finance Analyst
        Devised an improved financial reporting framework compliant with SEC regulations, leading to a 25% improvement in report submission timeline.
        Conducted comprehensive ROI analysis for proposed capital investments, leading to a more targeted allocation of the $30M budget.
        Resume Worded August 2012 - December 2015
        Finance Analyst
        Implemented a continuous improvement program for financial processes, achieving a 15% improvement in overall department efficiency.
        Created detailed financial projections for new business lines, contributing to a successful launch that exceeded revenue expectations by 20% in the first year.
        Coached.com May 2009 - July 2012
        Financial Auditor
        Executed field audits that led to the recovery of $500,000 in mismanaged funds, directly impacting the bottom line.
        EDUCATION
        Resume Worded Institute June 2014
        Chartered Financial Analyst (CFA) - Level III
        Completed vigorous finance program and achieved the final stage of CFA credentialing.
        Resume Worded Academic Center May 2011
        Master of Business Administration (MBA) - Finance
        Graduated with distinction, focusing on corporate finance and investment strategies.
        """,
        "location": None,
        "salary_desired": None,
        "education": None,
        "experience": 0
    },
    {
        "name": "PERSON10",
        "description": """
        EXPERIENCE
        Wells Fargo January 2018 - Present
        Finance Director
        Orchestrated the strategic realignment of the company's $200M capital investment plan, yielding a 12% improvement in ROI across all projects.
        Negotiated with technology providers to incorporate AI-driven analytics into financial processes, decreasing quarterly budget discrepancies by 18%.
        Championed a financial literacy initiative that increased employee investment in the company 401(k) plan by 25%.
        Cultivated a culture of data-driven decision making that reduced operational expenses by $5M without compromising quality or service.
        Bank of America June 2013 - December 2017
        Finance Manager
        Revamped cross-departmental collaboration protocols which enhanced forecasting reliability and contributed to a 30% reduction in fiscal quarter end closing times.
        Formulated a risk mitigation strategy for foreign exchange exposure, preserving $1M in revenue during a period of significant currency fluctuations.
        Resume Worded March 2009 - May 2013
        Senior Finance Analyst
        Designed a custom financial analysis tool that improved the tracking of project costs by 40%, greatly enhancing project budget adherence.
        Initiated a cost-saving program that eliminated $250,000 in annual redundant expenditures through strategic vendor negotiations.
        Coached.com July 2005 - February 2009
        Finance Analyst
        Played a key role in devising a financial plan that supported a company merger, contributing to a seamless integration with no financial disruptions.
        EDUCATION
        Resume Worded Institute May 2016
        Executive Master of Business Administration (EMBA)
        Focus on Strategic Finance Leadership
        Resume Worded Academic Center August 2010
        Chartered Financial Analyst (CFA) - Level II
        Part-time study alongside full-time finance role
        SKILLS
        Financial Analysis: Variance Analysis, NPV/IRR, Cash Flow Forecasting, Budgeting, Monte Carlo Simulation, Capital Asset Pricing Model
        Financial Software: SAP, Oracle Financials, QuickBooks, Hyperion, Bloomberg Terminal, Advanced Excel
        Data Analytics: SQL, Power BI, Tableau, SAS, Financial Modeling, Pivot Tables
        Regulatory Compliance: SOX, Dodd-Frank, GAAP, Basel III, FASB Standards Implementation, AML
        OTHER
        Certifications: Certified Public Accountant (CPA), Certified Management Accountant (CMA)
        Professional Development: Advanced Risk Management Program, Financial Data Analysis Workshop
        Awards: Finance Leader of the Year 2020 - Bank of America, Wells Fargo Excellence in Leadership Award 2019
        Industry Contributions: Panelist at the National Finance Summit 2021, Published author in the 'Journal of Strategic Finance'
        """,
        "location": None,
        "salary_desired": None,
        "education": None,
        "experience": 0
    },
    {
        "name": "PERSON11",
        "description": """
        Content Writer
        City, Country  •  (123) 456-789  •  yourname@resumeworded.com  •  linkedin.com/in/your-profile
        EXPERIENCE
        Coached.com January 2020 - Present
        Senior Content Writer
        Orchestrated the development and implementation of a comprehensive content marketing strategy, leading to a 30% increase in web traffic and a 20% boost in conversion rates.
        Crafted and executed an SEO-driven content calendar that resulted in a 25% uplift in organic search rankings for targeted keywords within a six-month period.
        Spearheaded a team of 5 writers, enhancing overall teamwork through the adoption of collaborative writing tools, improving productivity by 15%.
        Conducted data analysis on user engagement that informed content revisions, yielding a 40% improvement in average time spent on page.
        Initiated a robust guest blogging campaign that expanded brand reach and contributed to a 10% growth in subscriber base within a year.
        Google May 2017 - December 2019
        Content Writer
        Produced 300+ compelling tech-related articles, leading to a 35% increase in shared content and a 50% boost in user engagement.
        Implemented A/B testing for headlines and CTAs, which increased click-through rates by 17% within the first quarter.
        Collaborated with the Product Team to create accurate and informative product guides that decreased customer service inquiries by 22%.
        Resume Worded January 2015 - April 2017
        Copywriter
        Revamped product descriptions across all platforms, resulting in a 20% upswing in sales metrics within the first year.
        Led a cross-functional initiative to align brand messaging, which improved content consistency and aided in a 15% increase in overall brand recognition.
        Designed and implemented an email marketing campaign that rejuvenated a stagnant subscriber list, achieving a steady 12% monthly growth in audience engagement.
        Amazon June 2013 - December 2014
        Junior Content Writer
        Generated over 200 product-related articles, contributing to a 10% rise in product page conversions and a 15% increase in average order value.
        Implemented keyword optimization strategies that led to a 20% increase in organic search traffic for targeted product categories.
        EDUCATION
        Resume Worded Academic Center May 2019
        Master of Business Administration (MBA) - Marketing
        Concentration in Digital Content Strategy
        Resume Worded University June 2013
        Bachelor of Arts - English Literature
        Summa Cum Laude
        President of the Writers' Association
        SKILLS
        Content Management Systems: WordPress, Joomla, Drupal, Wix, Squarespace, Magento
        SEO & Analytics Tools: Google Analytics, SEMrush, Moz, Ahrefs, Yoast SEO, Google Search Console
        Writing & Editing: AP Style, Chicago Manual, Grammarly, Hemingway, Copyscape, ProWritingAid
        Graphic Design & Video Editing: Adobe Creative Suite, Canva, Final Cut Pro, InVision, Sketch
        OTHER
        Certifications: HubSpot Content Marketing Certified, Google Ads Search Certification
        Professional Development: Advanced Copywriting Workshop, Digital Marketing Bootcamp
        Publications: E-book author: 'Content Writing Essentials: Tips & Strategies for Winning in the Digital Space'
        Speaking Engagements: Panelist at WriteCon 2021, Keynote Speaker at Digital Market World Forum 2022
        """,
        "location": None,
        "salary_desired": None,
        "education": None,
        "experience": 0
    },
    {
        "name": "PERSON12",
        "description": """
        EXPERIENCE
        Facebook March 2018 - Present
        Content Writer Specialist
        Designed a viral content strategy that led to a post exceeding 1 million shares, increasing brand visibility and website referral traffic by 50%.
        Pioneered a social media content series that grew followers on the platform by 200,000 within a year through consistent, high-quality content delivery.
        Created a comprehensive brand storytelling guide that was adopted company-wide, enhancing content cohesion and helping define brand voice.
        Analyzed user data to personalize content, which resulted in a 30% increase in engagement rates for targeted demographics.
        Led content audits that identified and resolved gaps, boosting overall content suite effectiveness by 18%.
        Resume Worded August 2015 - February 2018
        Content Creator
        Developed an infographic series that supported a 25% improvement in website engagement and a 40% increase in shares on social media.
        Fostered a partnership with influencers leading to a 15% rise in content reach and a 22% increase in lead generation over a six-month period.
        Revamped the email newsletter strategy, resulting in a 35% surge in click-through rates and a 20% increase in open rates.
        HubSpot October 2012 - July 2015
        Digital Content Assistant
        Managed a content management system migration without any downtime, maintaining content integrity and boosting site performance by 10%.
        Contributed to a content partnership that increased website backlinks by 30%, significantly improving domain authority and SEO rankings.
        EDUCATION
        Resume Worded Institute May 2014
        Master of Arts in New Media and Digital Content
        Thesis on 'The Evolution of Social Media Content Engagement'
        Resume Worded University June 2011
        Bachelor of Science in Marketing
        Minored in Creative Writing and Multimedia Design
        Awarded 'Marketing Innovator of the Year' by faculty
        """,
        "location": None,
        "salary_desired": None,
        "education": None,
        "experience": 0
    },
    {
        "name": "PERSON13",
        "description": """
        EXPERIENCE
        Twitter April 2019 - Present
        Lead Content Writer
        Directed the content strategy overhaul that resulted in a 60% uptick in daily active users through targeted, interactive content initiatives.
        Coordinated with the analytics team to refine content targeting, increasing user relevance and retention by 25%.
        Initiated and conducted weekly content brainstorming sessions that resulted in a 50% increase in content production without sacrificing quality.
        Devised a real-time content tracking system, elevating content responsiveness and user interaction by 35%.
        Launched a multi-channel brand campaign that fortified the company’s presence across social platforms, augmenting user base by 100,000 within 4 months.
        Coached.com January 2016 - March 2019
        SEO Content Writer
        Improved long-tail keyword rankings by 70%, leading to a 45% increase in organic traffic within the first year of strategy implementation.
        Collaborated with the web development team to enhance website architecture, resulting in a 30% faster page load time and a 20% reduction in bounce rates.
        Authored an SEO guidebook adopted by the content team to uniformly optimize blog posts, doubling the rate at which new content ranked on SERPs.
        The Huffington Post August 2013 - December 2015
        Blogger
        Generated content that consistently ranked in the top 10% of most-read articles site-wide, driving a 15% increase in monetizable interactions.
        EDUCATION
        Resume Worded Institute May 2015
        Master of Arts in English and New Media
        Thesis on 'The Impact of Social Media on Modern Journalism'
        Resume Worded University May 2011
        Bachelor of Arts in Communications
        Summa Cum Laude
        Awarded the Top Communicator Award (2011)
        SKILLS
        Content Creation: Web Content, Blogging, SEO Optimization, Keyword Research, Social Media Copywriting, Editorial Strategy
        Digital Marketing Tools: Google Analytics, SEMrush, Moz, Ahrefs, HubSpot, Marketo
        Content Management Systems: WordPress, Joomla, Drupal, Magento, Squarespace, Wix
        Additional Skills: Proofreading, Copy Editing, HTML Basics, CSS Basics, Content Scheduling, Image Editing
        OTHER
        Certifications: Google Analytics Certified (2020), Advanced SEO Certification from Moz (2018)
        Publications: Contributor to 'Content Marketing Insights' eBook (2021), Featured in 'SEO Experts Round-Up' (2019)
        Projects: Managed end-to-end content strategy for a viral marketing campaign, 'Hashtag Challenge (2020)'
        Conferences: Speaker at the Digital Marketing World Forum (2019), Attendee at the Content Marketing Conference (2018)
        """,
        "location": None,
        "salary_desired": None,
        "education": None,
        "experience": 0
    },
    {
        "name": "PERSON14",
        "description": """
        Photographer
        City, Country  •  (123) 456-789  •  yourname@resumeworded.com  •  linkedin.com/in/your-profile
        EXPERIENCE
        Resume Worded January 2021 - Present
        Photographer
        Increased client satisfaction by 30% through the implementation of a mood board system to capture client visions accurately
        Generated over $150,000 in annual revenue by securing contracts with high-profile clients and maintaining long-term business relationships
        Reduced editing time by 40% with the introduction of new Lightroom presets tailored to various photography styles
        Documented more than 200 weddings, consistently delivering quality images 3 days ahead of schedule
        Improved social media engagement by 50% through strategic use of Instagram Stories and targeted adverts
        Adobe June 2018 - December 2020
        Junior Photographer
        Built a portfolio of over 100 portraits, resulting in a 25% increase in client bookings year over year
        Collaborated with a team of 5 editors to finalize images, speeding up the delivery process by 20%
        Implemented a new client feedback system that received a 98% satisfaction rating
        Captured and edited over 50 corporate events, leading to frequent re-engagements by clients
        Getty Images August 2015 - May 2018
        Photography Assistant
        Assisted in the setup and breakdown of photo shoots, improving efficiency by 15%
        Handled photo retouching and enhancements for over 300 images per week with a 99% approval rate
        Utilized Adobe Photoshop and Lightroom to create consistent quality across all projects
        Coached.com June 2014 - July 2015
        Intern
        Supported senior photographers on location shoots and in-studio sessions, increasing delivery speed by 25%
        Managed photographic equipment inventory, ensuring 100% equipment availability for all sessions
        Collaborated in editing over 1,000 images, enhancing image quality by maintaining attention to detail
        EDUCATION
        Resume Worded Institute May 2017
        Master of Fine Arts - Photography
        Thesis on 'The Impact of Digital Evolution on Photographic Artistry'
        Resume Worded University May 2014
        Bachelor of Arts - Visual Arts
        Cum Laude graduate
        Part-time (concurrent with Intern position at Coached.com)
        SKILLS
        Photography Software: Adobe Photoshop (Expert), Lightroom (Expert), Capture One (Expert), DxO PhotoLab (Advanced), Photoshop Elements (Advanced), Affinity Photo (Intermediate)
        Camera Equipment: DSLR Cameras (Nikon, Canon), Mirrorless Cameras (Sony, Fujifilm), Drone Operation (DJI), Gimbal Stabilizers, Lighting Kits, Audio Equipment
        Photography Techniques: Portrait Photography, Landscape Photography, Wedding Photography, Commercial Product Photography, Event Photography, Photojournalism
        Other Photography Skills: Digital Printing, Color Theory, Image Composition, Visual Storytelling, Photo Editing, Archiving
        OTHER
        Certifications: Certified Professional Photographer (CPP) - Professional Photographers of America (PPA)
        Awards: Adobe Creativity Scholarship recipient, 'Editor's Choice' Award - Getty Images (2017)
        Volunteering: Volunteer Photographer - Open Hearts Shelter, Photo Workshop Instructor - Youth Arts Initiative
        Publications: Contributing Photographer - National Geographic Traveler, Visual Arts Journal - Featured Photo Essay (Spring 2019 issue)
        """,
        "location": None,
        "salary_desired": None,
        "education": None,
        "experience": 0
    },
    {
        "name": "PERSON15",
        "description": """
        EXPERIENCE
        Coached.com March 2020 - Present
        Photographer
        Enhanced studio operational efficiency by 20% by introducing a digital booking and workflow management system
        Achieved a 50% click-through rate on email campaigns by integrating compelling visual content
        Directed and covered 150+ events including weddings, corporate functions, and personal celebrations, ensuring timely delivery of high-quality images
        Increased overall client satisfaction by 35% through meticulous pre-shoot consultations and post-shoot follow-ups
        Grew Instagram following from 2,000 to 15,000 through consistent posting and user engagement strategies
        Self-Employed February 2017 - February 2020
        Freelance Photographer
        Managed comprehensive photography projects for 80+ clients, leading to 100% client retention
        Developed a unique visual style that gained recognition in local and international photography competitions
        Negotiated contracts and pricing with clients, resulting in a 40% increase in annual earnings
        Implemented a client referral program that generated 25% of all new bookings
        Walmart July 2014 - January 2017
        Junior Photographer
        Successfully completed over 250 family and corporate photo sessions, increasing customer retention by 15%
        Utilized Adobe Lightroom to enhance photo quality, leading to a 20% reduction in post-production time
        Created promotional materials that boosted sales package uptake by 10%
        Resume Worded May 2013 - June 2014
        Intern
        Improved organizational workflow by designing a tracking system for equipment and assignments
        Participated in editing and retouching images for company portfolio, enhancing overall quality
        Assisted in scheduling and supervising shoots, contributing to a 98% project completion rate
        EDUCATION
        Resume Worded University May 2014
        Bachelor of Fine Arts - Photography
        Graduated with Honors
        Minor in Digital Media
        Resume Worded Institute March 2017
        Certified Professional Photographer (CPP)
        Certification awarded by Professional Photographers of America (PPA)
        """,
        "location": None,
        "salary_desired": None,
        "education": None,
        "experience": 0
    },
    {
        "name": "PERSON16",
        "description": """
        EXPERIENCE
        Adobe April 2019 - Present
        Photographer
        Identified and implemented a new client management software that increased scheduling efficiency by 50%
        Captured and edited over 300 high-resolution images monthly for online product catalogs, increasing online sales by 25%
        Collaborated with marketing team to create visual content for campaigns, contributing to a 40% increase in engagement rate
        Mentored junior photographers and interns, reducing their onboarding time by 30%
        Managed studio's social media, growing followers by 5,000 and increasing post interaction by 20% within a year
        Getty Images January 2016 - March 2019
        Junior Photographer
        Generated over $100,000 in revenue by capturing 200+ events, consistently meeting client expectations
        Leveraged advanced photo editing tools to enhance image quality, resulting in a 95% client approval rate
        Coordinated with clients to understand and fulfill their vision, achieving a 98% satisfaction score
        Introduced a new workflow that reduced photo processing time by 30%, enabling faster delivery
        Coached.com September 2014 - December 2015
        Photography Assistant
        Supported senior photographers during high-profile shoots, contributing to a 20% increase in shoot productivity
        Organized and maintained photographic equipment, ensuring all gear was in optimal condition
        Handled the logistics for shoots, including location scouting and permits, to streamline project execution
        Resume Worded June 2013 - August 2014
        Intern
        Assisted senior photographers in the setup and execution of shoots, learning professional techniques
        Enhanced over 1,000 images using Adobe Lightroom and Photoshop, ensuring high-quality deliverables
        Contributed to the company's blog with articles on photography tips, attracting new clients
        EDUCATION
        Resume Worded Institute March 2019
        Certified Professional Photographer
        Studied advanced techniques in digital photography, lighting, and editing
        Resume Worded University May 2014
        Bachelor of Fine Arts in Photography
        Concentration in Digital Imaging
        Part-time (during Internship at Resume Worded)
        SKILLS
        Photography: Digital Photography, Portrait Photography, Event Photography, Photo Editing, Lighting Techniques, Image Composition
        Software: Adobe Photoshop (Expert), Adobe Lightroom (Expert), Capture One (Proficient), Adobe Illustrator (Intermediate)
        Camera Equipment: DSLRs, Mirrorless Cameras, Medium Format, Camera Lenses, Off-Camera Flash, Tripods & Rigging
        Post-Processing: Color Correction, Batch Processing, Retouching, HDR Photography, Panoramic Stitching, File Management
        OTHER
        Awards: Recipient of The International Photography Award (2020)
        Exhibitions: Featured in National Geographic Traveler Exhibition (2021), Solo Exhibition 'Urban Stories' at Resume Worded Gallery (2018)
        Professional Memberships: Member of Professional Photographers of America, National Press Photographers Association
        """,
        "location": None,
        "salary_desired": None,
        "education": None,
        "experience": 0
    }
]

import pandas as pd
import numpy as np
from transformers import BertTokenizer, BertModel
import torch
from sklearn.metrics.pairwise import cosine_similarity

def extract_features(text, tokenizer, model):
    """Extract BERT features from text"""
    inputs = tokenizer(text, return_tensors='pt', max_length=512, truncation=True, padding='max_length')
    with torch.no_grad():
        outputs = model(**inputs)
    return outputs.last_hidden_state.mean(dim=1).squeeze().numpy()

def calculate_requirement_score(employer, candidate):
    """Calculate score based on specific requirements"""
    score = 0
    total_criteria = 0

    # Salary match
    if employer.get('salary_range') and candidate.get('salary_desired'):
        total_criteria += 1
        if employer['salary_range'][0] <= candidate['salary_desired'] <= employer['salary_range'][1]:
            score += 1

    # Education match
    if employer.get('education') and candidate.get('education'):
        total_criteria += 1
        if candidate['education'].lower() in employer['education'].lower():
            score += 1

    # Experience match
    if employer.get('experience') is not None:
        total_criteria += 1
        candidate_exp = candidate.get('experience', 0)
        if candidate_exp >= employer['experience']:
            score += 1

    # Location match
    if employer.get('location') and candidate.get('location'):
        total_criteria += 1
        if candidate['location'].lower() in employer['location'].lower():
            score += 1

    # If no criteria were checked, return 1 to not penalize missing information
    return score / total_criteria if total_criteria > 0 else 1

def rank_candidates(employers, candidates):
    """Rank candidates for each job posting"""
    # Initialize BERT
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
    model = BertModel.from_pretrained('bert-base-uncased')

    rankings = {}

    for employer in employers:
        print(f"\nAnalyzing candidates for: {employer['title']}")
        rankings[employer['title']] = []

        # Get employer job description features
        job_features = extract_features(employer['description'], tokenizer, model)

        for candidate in candidates:
            # Get candidate description features
            candidate_features = extract_features(candidate['description'], tokenizer, model)

            # Calculate text similarity score
            similarity_score = cosine_similarity(
                job_features.reshape(1, -1),
                candidate_features.reshape(1, -1)
            )[0][0]

            # Calculate requirements match score
            req_score = calculate_requirement_score(employer, candidate)

            # Calculate final score (weighted average)
            final_score = (similarity_score * 0.6) + (req_score * 0.4)

            rankings[employer['title']].append({
                'name': candidate['name'],
                'similarity_score': similarity_score,
                'requirement_score': req_score,
                'final_score': final_score
            })

        # Sort candidates by final score
        rankings[employer['title']] = sorted(
            rankings[employer['title']],
            key=lambda x: x['final_score'],
            reverse=True
        )

    return rankings

def print_rankings(rankings):
    """Print formatted rankings for each job"""
    for job_title, candidates in rankings.items():
        print(f"\n{'='*80}")
        print(f"Job Position: {job_title}")
        print(f"{'='*80}")
        print(f"{'Rank':<6}{'Name':<15}{'Text Match':<15}{'Req Match':<15}{'Final Score':<15}")
        print('-' * 80)

        for i, candidate in enumerate(candidates, 1):
            print(f"{i:<6}{candidate['name']:<15}{candidate['similarity_score']:.3f}{'':>7}"
                  f"{candidate['requirement_score']:.3f}{'':>7}{candidate['final_score']:.3f}{'':>7}")
        print()

# Main execution
if __name__ == "__main__":
    rankings = rank_candidates(employers, candidates)
    print_rankings(rankings)

